#!/usr/bin/env python
"""
manage.py
---------
Django's command-line utility for administrative tasks such as:
    python manage.py runserver
    python manage.py makemigrations
    python manage.py migrate
    python manage.py createsuperuser
This file is auto-generated by Django but kept here unmodified,
as is standard practice.
"""
import os
import sys


def main():
    """Run administrative tasks."""
    # Point Django to our settings module
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cloud_storage.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
